# Kernel Support Vector Machine_Classification

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline


# Importing the dataset

In [2]:
df = pd.read_csv('Social_Network_Ads.csv')
df.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [3]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

# Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 10)

# Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
scaler = StandardScaler()

In [8]:
X_train = scaler.fit_transform(X_train)

In [9]:
X_test =scaler.transform(X_test)

# Training the SVM model on the Training Data set

In [10]:
from sklearn.svm import SVC

In [13]:
svc = SVC(kernel= 'rbf', random_state= 10)

In [14]:
svc.fit(X_train,y_train)

SVC(random_state=10)

# Predicting a new result

In [15]:
pred = svc.predict

In [16]:
pred(scaler.transform([[30,87000]]))

array([0], dtype=int64)

# Predicting the Test set results

In [17]:
pred = pred(X_test)

In [18]:
print(np.concatenate((pred.reshape(len(pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]]


# Evaluating Model results

In [19]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [20]:
print(confusion_matrix(y_test,pred))

[[64  5]
 [ 1 30]]


In [21]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.98      0.93      0.96        69
           1       0.86      0.97      0.91        31

    accuracy                           0.94       100
   macro avg       0.92      0.95      0.93       100
weighted avg       0.95      0.94      0.94       100



In [22]:
print(accuracy_score(y_test,pred))

0.94
